gem 'celluloid', :git => 'git://github.com/celluloid/celluloid.git'
gem 'celluloid-io', :git => 'git://github.com/celluloid/celluloid-io.git'
gem 'reel', :git => 'git://github.com/celluloid/reel.git'
gem 'dcell', :git => 'git://github.com/celluloid/dcell.git'
gem 'celluloid-zmq', :git => 'git://github.com/celluloid/celluloid-zmq.git'
gem 'websocket_parser', :git => 'git://github.com/afcapel/websocket_parser.git'